edit_uri: 'edit/main/docs'
repo_url: https://github.com/color-rise/chainblocks-euler/
site_name: Project Euler's problems solved with chainblocks
site_url:
copyright: Copyright © 2022 Color Rise EURL
extra:
  generator: false
  social:
    - icon: fontawesome/solid/building
      link: https://www.color-rise.xyz
      name: Color Rise homepage
    - icon: fontawesome/brands/github
      link: https://github.com/color-rise
      name: Color Rise is on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/colorRise
      name: Follow us on Twitter
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/color-rise/
      name: Company profile on LinkedIn
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  - awesome-pages:
      strict: false
  - macros
theme:
  # favicon: assets/images/favicon.svg
  features:
    - navigation.indexes
    - navigation.expand
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    # - toc.integrate
  font:
    code: Fira Code
    text: Montserrat
  language: en
  # logo: assets/images/logo.svg
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
use_directory_urls: true
