name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, ready_for_review, review_requested]
  workflow_dispatch:

jobs:

  #
  # Build shards for Windows
  #
  shards-build:
    uses: fragcolor-xyz/shards/.github/workflows/build-windows.yml@devel
    secrets: inherit
    with:
      bitness: 64bits
      build-type: Release

  #
  # Run problems
  #
  problems-run:
    needs: shards-build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: shards-win64 Release
          path: src/problems
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          release: false
          path-type: inherit
      - name: Run problems
        shell: msys2 {0}
        run: |
          cd src/problems
          for i in $(find -name '*.edn');
          do
            echo "Running '$i'";
            ./shards.exe "$i" > >(tee "$i.log");
          done  
      - name: Upload problems logs
        uses: actions/upload-artifact@v2
        with:
          name: problems-logs
          path: src/problems/**/*.log
          if-no-files-found: error

  #
  # Build the website
  #
  website:
    needs: problems-run
    uses: ./.github/workflows/website.yml
    secrets: inherit
    with:
      publish: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
